### ISSUE TITLE
Dprint hangs forever on arm64 linux

### ISSUE THREAD

**Issue by surma** [dprint/dprint-plugin-prettier#89]
```
$ dprint fmt
[dprint-plugin-prettier]
Error reading stdout message: failed to fill whole buffer
... [after a couple of seconds] ...
WARNING: Formatting is slow for <some file>
```

I only see this on Linux. On MacOS, it runs fine.

```
$ dprint --version
dprint 0.48.0
```

<details>
<summary> <code>dprint.json</code> </summary>

```
{
  "json": {},
  "markdown": {},
  "exec": {
    "commands": [
      {
        "command": "rustfmt --edition 2021 --config unstable_features=true --config format_code_in_doc_comments=true",
        "exts": ["rs"]
      },
      {
        "command": "nixfmt",
        "exts": ["nix"]
      }
    ]
  },
  "prettier": {},
  "excludes": ["node_modules/**", "dist/**", "vendor/**", "apis/*.d.ts", "app/artifacts/fixtures/**"],
  "plugins": [
    "https://plugins.dprint.dev/json-0.19.1.wasm",
    "https://plugins.dprint.dev/markdown-0.16.3.wasm",
    "https://plugins.dprint.dev/prettier-0.46.1.json@e5bd083088a8dfc6e5ce2d3c9bee81489b065bd5345ef55b59f5d96627928b7a",
    "https://plugins.dprint.dev/exec-0.5.0.json@8d9972eee71fa1590e04873540421f3eda7674d0f1aae3d7c788615e7b7413d0"
  ]
}
```
</details>

**Comment by dsherret** [comment]
Can you run with `dprint fmt --verbose`? Is there a certain file this occurs on or does this happen everywhere?

Also, I just released a version that uses an updated version of all the dependencies, so maybe it's fixed there (try `dprint config update` then `dprint fmt`).

**Comment by surma** [comment]
I updated the plugins, the error remains, sadly :S

The file is always the same one _per repository_. In one of the repository it’s `missing-types.d.ts`, in another repo it’s `dedent.js`. I am attaching the contents of both here, although I suspect it’s got nothing to do with the actual contents.

Here’s what the verbose output looks like:

<details>
<summary>Verbose log</summary>

```
dprint fmt --verbose
[DEBUG] Reading file: /home/surma/.cache/dprint/cache/plugin-cache-manifest.json
[DEBUG] Creating directory: /home/surma/.cache/dprint/cache/locks
[DEBUG] Checking path exists: /home/surma/src/github.com/surma/blog/dprint.json
[DEBUG] Reading file: /home/surma/src/github.com/surma/blog/dprint.json
[DEBUG] Reading file: /home/surma/.cache/dprint/cache/plugins/dprint-plugin-json/0.19.1-5.0.2-aarch64-7370067139647032066
[DEBUG] Reading file: /home/surma/.cache/dprint/cache/plugins/dprint-plugin-markdown/0.16.3-5.0.2-aarch64-7370067139647032066
[DEBUG] Checking path exists: /home/surma/.cache/dprint/cache/plugins/dprint-plugin-prettier/0.46.1/aarch64/dprint-plugin-prettier
[DEBUG] Checking path exists: /home/surma/.cache/dprint/cache/plugins/dprint-plugin-exec/0.5.0/aarch64/dprint-plugin-exec
[DEBUG] Creating instance of dprint-plugin-json
[DEBUG] Creating instance of dprint-plugin-markdown
[DEBUG] Creating instance of dprint-plugin-prettier
[DEBUG] Creating instance of dprint-plugin-exec
[DEBUG] Created instance of dprint-plugin-json in 1ms
[DEBUG] Created instance of dprint-plugin-markdown in 1ms
[DEBUG] Created instance of dprint-plugin-exec in 2ms
[DEBUG] Created instance of dprint-plugin-prettier in 3ms
[DEBUG] Globbing: GlobPatterns { arg_includes: None, config_includes: Some([GlobPattern { relative_pattern: "**/*.{md,css,sublime-workspace,wxss,scss,rviz,sublime-mousemap,jake,sublime-commands,graphqls,livemd,less,rs,xsjslib,postcss,sublime-syntax,workbook,mcmeta,bones,gs,cts,webapp,sublime-completions,jss,gql,ssjs,importmap,hbs,mjml,markdown,html.hl,syntax,handlebars,yaml-tmlanguage,sublime-keymap,jsonc,gltf,sublime-build,jspre,sublime_metrics,yml,frag,code-workspace,sublime-macro,hta,jsm,4DProject,mdx,sjs,nix,jsb,yaml.sed,es,mkdn,geojson,json,mkdown,4DForm,tfstate,tfstate.backup,topojson,jscad,ts,es6,js.flow,avsc,yy,html,xht,sublime-project,xhtml,mts,scd,sublime-theme,javascript,xsjs,sublime-settings,mir,yml.mysql,yaml,component.html,vue,mkd,js,pac,pcss,sublime_session,reek,svelte,mdown,cjs,_js,jsfl,jslib,njs,tsx,webmanifest,code-snippets,sublime-menu,mjs,jsx,har,ice,yyp,json5,graphql,wxs,JSON-tmLanguage,htm,mdwn,inc,ronn}", base_dir: CanonicalizedPathBuf { path: "/home/surma/src/github.com/surma/blog" } }]), arg_excludes: None, config_excludes: [GlobPattern { relative_pattern: "node_modules/**", base_dir: CanonicalizedPathBuf { path: "/home/surma/src/github.com/surma/blog" } }, GlobPattern { relative_pattern: "dist/**", base_dir: CanonicalizedPathBuf { path: "/home/surma/src/github.com/surma/blog" } }, GlobPattern { relative_pattern: "vendor/**", base_dir: CanonicalizedPathBuf { path: "/home/surma/src/github.com/surma/blog" } }, GlobPattern { relative_pattern: "apis/*.d.ts", base_dir: CanonicalizedPathBuf { path: "/home/surma/src/github.com/surma/blog" } }, GlobPattern { relative_pattern: "app/artifacts/fixtures/**", base_dir: CanonicalizedPathBuf { path: "/home/surma/src/github.com/surma/blog" } }, GlobPattern { relative_pattern: "**/node_modules", base_dir: CanonicalizedPathBuf { path: "/home/surma/src/github.com/surma/blog" } }] }
[DEBUG] Checking path exists: /home/surma/src/github.com/surma/blog/.git
[DEBUG] Reading file: /home/surma/src/github.com/surma/blog/.gitignore
[DEBUG] Reading file: /home/surma/src/github.com/surma/blog/example/.gitignore
[DEBUG] Reading file: /home/surma/src/github.com/surma/blog/plugins/.gitignore
[DEBUG] Reading file: /home/surma/src/github.com/surma/blog/fs/.gitignore
[DEBUG] Reading file: /home/surma/src/github.com/surma/blog/example/layouts/.gitignore
[DEBUG] Reading file: /home/surma/src/github.com/surma/blog/example/pages/.gitignore
[DEBUG] Reading file: /home/surma/src/github.com/surma/blog/plugins/markdown/.gitignore
[DEBUG] Reading file: /home/surma/src/github.com/surma/blog/plugins/layout/.gitignore
[DEBUG] Reading file: /home/surma/src/github.com/surma/blog/example/pages/posts/.gitignore
[DEBUG] File(s) matched: GlobOutput { file_paths: ["/home/surma/src/github.com/surma/blog/package-lock.json", "/home/surma/src/github.com/surma/blog/dedent.js", "/home/surma/src/github.com/surma/blog/dprint.json", "/home/surma/src/github.com/surma/blog/frontmatter.js", "/home/surma/src/github.com/surma/blog/ssg.js", "/home/surma/src/github.com/surma/blog/package.json", "/home/surma/src/github.com/surma/blog/fs/node.js", "/home/surma/src/github.com/surma/blog/fs/virtual.js", "/home/surma/src/github.com/surma/blog/fs/index.test.js", "/home/surma/src/github.com/surma/blog/fs/index.js", "/home/surma/src/github.com/surma/blog/example/layouts/main.js", "/home/surma/src/github.com/surma/blog/example/layouts/post.js", "/home/surma/src/github.com/surma/blog/example/layouts/landing-page.js", "/home/surma/src/github.com/surma/blog/example/pages/index.md", "/home/surma/src/github.com/surma/blog/plugins/markdown/index.js", "/home/surma/src/github.com/surma/blog/plugins/layout/index.js", "/home/surma/src/github.com/surma/blog/example/pages/posts/second.md", "/home/surma/src/github.com/surma/blog/example/pages/posts/hidden.md", "/home/surma/src/github.com/surma/blog/example/pages/posts/first.md"], config_files: [] }
[DEBUG] Finished globbing in 3ms
[DEBUG] Creating directory: /home/surma/.cache/dprint/cache/incremental
[DEBUG] Reading file: /home/surma/.cache/dprint/cache/incremental/14393587557831000570
[DEBUG] Checking path exists: /home/surma/.cache/dprint/cache/incremental/14393587557831000570
[DEBUG] Running for config: /home/surma/src/github.com/surma/blog/dprint.json
[DEBUG] Max threads: 4
Thread count: 1
[DEBUG] Reading file: /home/surma/src/github.com/surma/blog/dedent.js
[dprint-plugin-prettier]
Error reading stdout message: failed to fill whole buffer
[dprint]
[DEBUG] CPU usage: 0%
[DEBUG] CPU usage: 0%
[DEBUG] CPU usage: 3%
WARNING: Formatting is slow for /home/surma/src/github.com/surma/blog/dedent.js
[DEBUG] CPU usage: 0%
[DEBUG] CPU usage: 1%
```

</details>

<details>
<summary><code>missing-types.d.ts</code></summary>

```ts
declare module "docs:*" {
  const docs: import("~shared/doc-parser").Documentation;
  export default docs;
}

declare module "json:*" {
  const obj: any;
  export default obj;
}
```

</details>

<details>
<summary><code>dedent.js</code></summary>

```js
/**
 * Removes common leading whitespace from every line in a template literal string
 * while preserving internal indentation structure.
 *
 * @param {TemplateStringsArray} strings
 * @param {any[]} values
 * @returns {string}
 * @example
 * const result = dedent`
 *     Hello
 *       Indented line
 *     Another line
 * `;
 * // Result:
 * // Hello
 * //   Indented line
 * // Another line
 */
export function dedent(strings, ...values) {
  // Combine the template literal parts
  const raw = String.raw(strings, ...values);

  // Split into lines and remove empty lines at start/end
  const lines = raw.split("\n");
  while (lines.length > 0 && lines[0].trim() === "") lines.shift();
  while (lines.length > 0 && lines[lines.length - 1].trim() === "") lines.pop();

  if (lines.length === 0) return "";

  // Find the minimum indentation level (excluding empty lines)
  const leadingWhitespace = lines
    .filter((line) => line.trim().length > 0)
    .map((line) => line.match(/^[ \t]*/)?.[0].length ?? Infinity);

  const minIndent = Math.min(...leadingWhitespace);

  // Remove the common indentation from all lines
  return lines.map((line) => line.slice(minIndent)).join("\n");
}
```

</details>

**Comment by dsherret** [comment]
Thanks! I was able to reproduce on arm64 linux. Unfortunately GHA doesn't have arm64 linux runners so I can't test in gha. Will look into fixing this soon.

**Comment by dsherret** [comment]
Should be fixed now.

I found it worked fine when I built from source locally, so instead of using [cross](https://github.com/cross-rs/cross) I changed it to build on buildjet. That seems to have fixed the issue for me.

This is the huge negative to providing binaries instead of portable code (I tried to develop a version of this plugin that executes with node, but I found that node was just [way to slow with workers compared to Deno](https://github.com/dprint/dprint/issues/702#issuecomment-1633233013) and found people were having similar findings online).

**Comment by surma** [comment]
Confirmed fixed! Thank you kindly.
